<a href="https://colab.research.google.com/github/Rakeshsharma0068/DSA/blob/master/LAB7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Matrix and Vector Products


## 1.1 Dot Product, Inner Product and Outer Product


In [42]:
import time
start_time=time.time()
import numpy as np
print(np.dot(3,4))
print(np.dot([2, 3], [2, 3]))
print(np.dot([[2, 3]], [2, 3])) 
print(np.dot([2j, 3j], [2j, 3j]))
a = [[1, 0], [0, 1]]  
b = [[4, 1], [2, 2]]
print(np.dot(a,b)) #instead of 2*2 matrix give matrices of size 2000*2000(all values 1)
print(np.vdot(a,b)) #How vdot is working ?
print(np.inner(np.eye(10),3))
a=np.array([1,2,3,4,5,6])
b=np.array([1,2,3,4,5,6])
print(np.outer(a,b))
print(np.inner(a,b)) #change b to np.array([1,2,3])
print("Execution time ",time.time()-start_time)

12
13
[13]
(-13+0j)
[[4 1]
 [2 2]]
6
[[3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]]
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
91
Execution time  0.003309965133666992


instead of 2 * 2 matrix give matrices of size 2000*2000(all values 1)

In [35]:
start_time=time.time()
a = np.ones((2000,2000))
b = np.ones((2000,2000))
print(np.dot(a,b))
print("Execution time ",time.time()-start_time)

[[2000. 2000. 2000. ... 2000. 2000. 2000.]
 [2000. 2000. 2000. ... 2000. 2000. 2000.]
 [2000. 2000. 2000. ... 2000. 2000. 2000.]
 ...
 [2000. 2000. 2000. ... 2000. 2000. 2000.]
 [2000. 2000. 2000. ... 2000. 2000. 2000.]
 [2000. 2000. 2000. ... 2000. 2000. 2000.]]
Execution time  0.4953157901763916


**How vdot is working ?**

Compared to dot, vdot handles complex numbers in a different manner. if the first argument is complex then complex conjugate of the first arugment is used for the calculation of the dot product.

 change b to np.array([1,2,3])

In [36]:
a=np.array([1,2,3,4,5,6])
b=np.array([1,2,3])
print(np.outer(a,b))
print(np.inner(a,b)) 


[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


ValueError: ignored

## 1.2 Matrix Multiplication, Trace, Diagonal and Transpose

In [37]:
import time
start_time=time.time()
import numpy as np
a = [[1, 0], [0, 1]]  
b = [[4, 1], [2, 2]]
c=7
print("Dot Product of a and b is ",np.dot(a,b))
print("Dot Product of a and c is ",np.dot(a,c))
print("Matrix a multiplied by Matrix b is ",np.matmul(a,b)) #instead of b give c
print("Trace of a is ",np.trace(a))
print("Diagonal elements of a ",np.diag(a))
print("Transpose of b",np.transpose(b))
print("Execution time ",time.time()-start_time)

Dot Product of a and b is  [[4 1]
 [2 2]]
Dot Product of a and c is  [[7 0]
 [0 7]]
Matrix a multiplied by Matrix b is  [[4 1]
 [2 2]]
Trace of a is  2
Diagonal elements of a  [1 1]
Transpose of b [[4 2]
 [1 2]]
Execution time  0.0023851394653320312


instead of b give c

In [38]:
import time
start_time=time.time()
import numpy as np
a = [[1, 0], [0, 1]]  
b = [[4, 1], [2, 2]]
c=7
print("Dot Product of a and b is ",np.dot(a,b))
print("Dot Product of a and c is ",np.dot(a,c))
print("Matrix a multiplied by Matrix b is ",np.matmul(a,b))
print("Trace of a is ",np.trace(a))
print("Diagonal elements of a ",np.diag(a))
print("Transpose of b",np.transpose(b))
print("Execution time ",time.time()-start_time)

Dot Product of a and b is  [[4 1]
 [2 2]]
Dot Product of a and c is  [[7 0]
 [0 7]]
Matrix a multiplied by Matrix b is  [[4 1]
 [2 2]]
Trace of a is  2
Diagonal elements of a  [1 1]
Transpose of b [[4 2]
 [1 2]]
Execution time  0.006510496139526367


## 1.3 Sum, Mean and Variance

In [39]:
import time
start_time=time.time()
import numpy as np
a = [[1, 0], [0, 1]]  
b = [[4, 1], [2, 2]]
print("Sum of b is ",np.sum(b))
print("Rowwise sum of b is ",np.sum(b,axis=1)) #Try axis=0
print("Average of b is ",np.mean(b))
print("Rowwise average of b is ",np.mean(b,axis=1)) #Try axis=0
print("Variance of b is ",np.var(b))
print("Rowwise variance of b is ",np.var(b,axis=1)) #Try axis=0
print("Execution time ",time.time()-start_time)

Sum of b is  9
Rowwise sum of b is  [5 4]
Average of b is  2.25
Rowwise average of b is  [2.5 2. ]
Variance of b is  1.1875
Rowwise variance of b is  [2.25 0.  ]
Execution time  0.006849527359008789


In [ ]:
import time
start_time=time.time()
import numpy as np
a = [[1, 0], [0, 1]]  
b = [[4, 1], [2, 2]]
print("Sum of b is ",np.sum(b))
print("Rowwise sum of b is ",np.sum(b,axis=0)) 
print("Average of b is ",np.mean(b))
print("Rowwise average of b is ",np.mean(b,axis=0)) 
print("Variance of b is ",np.var(b))
print("Rowwise variance of b is ",np.var(b,axis=0)) 
print("Execution time ",time.time()-start_time)

## 1.4 Kronecker Product

In [9]:
import time
start_time=time.time()
import numpy as np
print(np.kron(np.eye(2), np.ones((2,2))))
print("Execution time ",time.time()-start_time)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]
Execution time  0.004508495330810547


# 2.Linear algebra Library

## 2.1 Power, Determinant, Inverse, Rank of a Matrix

In [10]:
import time
start_time=time.time()
import numpy as np 
a=np.array([[1 ,2],[1,4]])  #change [1,4] to [2,4]
print(np.linalg.matrix_power(a,3)) #Try 15 instead of 3
print(np.linalg.matrix_rank(a))
print(np.linalg.det(a)) #type output to int
print(np.linalg.inv(a))
print("Execution time ",time.time()-start_time)

[[13 46]
 [23 82]]
2
2.0
[[ 2.  -1. ]
 [-0.5  0.5]]
Execution time  0.029554367065429688


- change [1,4] to [2,4]


In [11]:
import time
start_time=time.time()
import numpy as np 
a=np.array([[1 ,2],[2,4]])  
print(np.linalg.matrix_power(a,3)) 
print(np.linalg.matrix_rank(a))
print(np.linalg.det(a)) 
print(np.linalg.inv(a))
print("Execution time ",time.time()-start_time)

[[ 25  50]
 [ 50 100]]
1
0.0


LinAlgError: ignored

- Try 15 insted of 3

In [12]:
import time
start_time=time.time()
import numpy as np 
a=np.array([[1 ,2],[1,4]])  
print(np.linalg.matrix_power(a,15)) 
print(np.linalg.matrix_rank(a))
print(np.linalg.det(a)) 
print(np.linalg.inv(a))
print("Execution time ",time.time()-start_time)

[[1049196317 3736768094]
 [1868384047 6654348458]]
2
2.0
[[ 2.  -1. ]
 [-0.5  0.5]]
Execution time  0.007770538330078125


Type output to int

In [13]:
import time
start_time=time.time()
import numpy as np 
a=np.array([[1 ,2],[1,4]])  
print(np.linalg.matrix_power(a,3)) 
print(np.linalg.matrix_rank(a))
print(np.linalg.det(a)) #type output to int
print(np.linalg.inv(a).astype(int))
print("Execution time ",time.time()-start_time)

[[13 46]
 [23 82]]
2
2.0
[[ 2 -1]
 [ 0  0]]
Execution time  0.010647058486938477


## 2.2 Solve the system of equations a + 2 b = 1 and 3 a + 5 * b = 2


In [14]:
import time
start_time=time.time()
import numpy as np 
A = np.array([[1, 2], [3, 5]]) #instead of [3,5] give [2,4]
B = np.array([1, 2])
X = np.linalg.solve(A, B)
print(X)
a=X[0]
b=X[1]
print(a,b)
print(np.allclose(np.dot(A, X), B)) #checking whether solution is true
print("Execution time ",time.time()-start_time)

[-1.  1.]
-0.9999999999999994 0.9999999999999997
True
Execution time  0.006349802017211914


instead of [3,5] give [2,4]

In [15]:
import time
start_time=time.time()
import numpy as np 
A = np.array([[1, 2], [2, 4]]) 
B = np.array([1, 2])
X = np.linalg.solve(A, B)
print(X)
a=X[0]
b=X[1]
print(a,b)
print(np.allclose(np.dot(A, X), B))
print("Execution time ",time.time()-start_time)

LinAlgError: ignored

## 2.3 Eigen Value and Eigen Vector


In [16]:
import time
start_time=time.time()
import numpy as np 
a=np.diag((1,2,3)) #change (1,2,3) to (1,2,3,4)
print(a)
w,v=np.linalg.eig(a)
print(w)
print(v)
print("Execution time ",time.time()-start_time)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Execution time  0.012073278427124023


change (1,2,3) to (1,2,3,4)

In [17]:
import time
start_time=time.time()
import numpy as np 
a=np.diag((1,2,3,4)) 
print(a)
w,v=np.linalg.eig(a)
print(w)
print(v)
print("Execution time ",time.time()-start_time)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1. 2. 3. 4.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Execution time  0.0055272579193115234


a=np.array([[1,2],[3,4]])

In [18]:
import time
start_time=time.time()
import numpy as np 
a=np.array([[1,2],[3,4]])
print(a)
w,v=np.linalg.eig(a)
print(w)
print(v)
print("Execution time ",time.time()-start_time)

[[1 2]
 [3 4]]
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Execution time  0.004335641860961914


# 3. Polynomials


## 3.1 Representing a polynomial and evaluating it's value


In [19]:
import time
start_time=time.time()
import numpy as np 
p = np.poly1d([1, 2, 3])
print(np.poly1d(p))
print(np.polyval(p,5))  #Evaluate polynomial at value 7
print(np.polyadd(p,p)) #try polysub, polydiv,polymul
print("Execution time ",time.time()-start_time)

   2
1 x + 2 x + 3
38
   2
2 x + 4 x + 6
Execution time  0.004155397415161133


In [20]:
import time
start_time=time.time()
import numpy as np 
p = np.poly1d([1, 2, 3])
print(np.poly1d(p))
print(np.polyval(p,7))  
print(np.polyadd(p,p)) 
print("Execution time ",time.time()-start_time)

   2
1 x + 2 x + 3
66
   2
2 x + 4 x + 6
Execution time  0.007470846176147461


polysub

In [21]:
import time
start_time=time.time()
import numpy as np 
p = np.poly1d([1, 2, 3])
print(np.poly1d(p))
print(np.polyval(p,5)) 
print(np.polysub(p,p)) 
print("Execution time ",time.time()-start_time)

   2
1 x + 2 x + 3
38
 
0
Execution time  0.01009225845336914


polydiv

In [22]:
import time
start_time=time.time()
import numpy as np 
p = np.poly1d([1, 2, 3])
print(np.poly1d(p))
print(np.polyval(p,5))  
print(np.polydiv(p,p))
print("Execution time ",time.time()-start_time)

   2
1 x + 2 x + 3
38
(poly1d([1.]), poly1d([0.]))
Execution time  0.007295370101928711


polymul

In [23]:
import time
start_time=time.time()
import numpy as np 
p = np.poly1d([1, 2, 3])
print(np.poly1d(p))
print(np.polyval(p,5)) 
print(np.polymul(p,p)) 
print("Execution time ",time.time()-start_time)

   2
1 x + 2 x + 3
38
   4     3      2
1 x + 4 x + 10 x + 12 x + 9
Execution time  0.0012733936309814453


In [24]:
import time
start_time=time.time()
import numpy as np
p = np.poly1d([1, -2, 1]) #Design polynomial to produce imaginary roots
print(p.c)  #print coefficients of polynomial
print(np.roots(p))
print("Execution time ",time.time()-start_time)

[ 1 -2  1]
[1. 1.]
Execution time  0.0050008296966552734


## 3.2 Least Square Polynomial fit


In [26]:
import time
start_time=time.time()
import numpy as np
x = np.array([0.0, 1.0, 2.0, 3.0,  4.0,  5.0])
y = np.array([0.0, 2.0, 4.0, 6.0, 8.0, 10.0])  #Clearly y=2x
z = np.polyfit(x, y,1) #Change 1 to 2
print(z)
print(np.poly1d(z)(7))
print("Execution time ",time.time()-start_time)

[ 2.00000000e+00 -8.46295243e-17]
13.999999999999996
Execution time  0.0012989044189453125


Change 1 to 2

In [27]:
import time
start_time=time.time()
import numpy as np
x = np.array([0.0, 1.0, 2.0, 3.0,  4.0,  5.0])
y = np.array([0.0, 2.0, 4.0, 6.0, 8.0, 10.0])  
z = np.polyfit(x, y,2)
print(z)
print(np.poly1d(z)(7))
print("Execution time ",time.time()-start_time)

[7.27501968e-17 2.00000000e+00 2.92686766e-15]
14.000000000000002
Execution time  0.0018849372863769531


1.Create 100 polynomials of following specification
First polynomial is x^99 + 1
Second polynomial is x^99 + x
.....
99'th polynomial is x^99 + x^98
100'th polynomial is x^99

In [28]:
matrix=[]
for i in range(0,100):
  row=[]
  for j in range(0,100):
    row.append(0) 
  matrix.append(row)
for i in range(0,99):
  if(i==0):
    print(i+1, "polynomial is x^99 + 1")
  else:
    print(i+1, "polynomial is x^99 + x^",i)
    matrix[i][99]=1
    matrix[i][i]=1
print(99, "polynomial is x^99 ")
matrix[98][98]=1


1 polynomial is x^99 + 1
2 polynomial is x^99 + x^ 1
3 polynomial is x^99 + x^ 2
4 polynomial is x^99 + x^ 3
5 polynomial is x^99 + x^ 4
6 polynomial is x^99 + x^ 5
7 polynomial is x^99 + x^ 6
8 polynomial is x^99 + x^ 7
9 polynomial is x^99 + x^ 8
10 polynomial is x^99 + x^ 9
11 polynomial is x^99 + x^ 10
12 polynomial is x^99 + x^ 11
13 polynomial is x^99 + x^ 12
14 polynomial is x^99 + x^ 13
15 polynomial is x^99 + x^ 14
16 polynomial is x^99 + x^ 15
17 polynomial is x^99 + x^ 16
18 polynomial is x^99 + x^ 17
19 polynomial is x^99 + x^ 18
20 polynomial is x^99 + x^ 19
21 polynomial is x^99 + x^ 20
22 polynomial is x^99 + x^ 21
23 polynomial is x^99 + x^ 22
24 polynomial is x^99 + x^ 23
25 polynomial is x^99 + x^ 24
26 polynomial is x^99 + x^ 25
27 polynomial is x^99 + x^ 26
28 polynomial is x^99 + x^ 27
29 polynomial is x^99 + x^ 28
30 polynomial is x^99 + x^ 29
31 polynomial is x^99 + x^ 30
32 polynomial is x^99 + x^ 31
33 polynomial is x^99 + x^ 32
34 polynomial is x^99 + x^ 33
35

2. Store the coefficients to a matrix of size 100 * 100


In [29]:
print("Coefficents of matrix are")
for i in range(0,100):
  for j in range(0,100):
    print(matrix[i][j],end="")
  print()

Coefficents of matrix are
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
0010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
0001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
0000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
0000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
0000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
0000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
0000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
00000000010000000000000000000000000000000000000000000000000000000

3. Find rank of 100*100 matrix

In [31]:
print("Rank = ", np.linalg.matrix_rank(matrix))

Rank =  98


4. Write a function to extract any particular block in that 100 *100 matrix


In [33]:
def extract(x,y,x1,y1):
  block=[]
  for i in range(y,y1):
    row=[]
    for j in range(x,x1):
       row.append(matrix[i][j])
    block.append(row)
  return block
print(extract(2,2,4,4))

[[1, 0], [0, 1]]


5. Find the inverse of first 3 by 3 matrix(starting from 0,0) of that 100*100 matrix

In [32]:
first=[]
for i in range(0,3):
  row=[]
  for j in range(0,3):
    row.append(matrix[i][j])
  first.append(row)

inverse_matrix = np.linalg.pinv(first)
print(inverse_matrix)


[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
